### PR TITLE
Add buble extension

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
Here's project link
https://gitlab.com/Rich-Harris/buble

**Comment by phated** [comment]
@TrySound thanks for sending this but that project is still insanely immature, I'm going to hold off for now to see if it gains traction.

**Comment by tkellen** [comment]
@phated I agree it's very immature, but I don't think it is our place to decide if something is popular enough to be included. As long as there isn't a conflict with an existing extension, I'm inclined to support anything people submit that is actually a project.

**Comment by TrySound** [comment]
Thanks, guys. Yeah, buble is very young. But as it's focused on small part and have an experience of another js-processing projects it's mostly complete. I use it in big production code and it works well. Also implementing buble as gulpfile processor can involve more people to let this project be improved.

**Comment by TrySound** [comment]
Thanks, Tyler. WIll you publish?

**Comment by tkellen** [comment]
I *just* did, like, a few seconds ago!

**Comment by TrySound** [comment]
Cool!

**Comment by WolfieZero** [comment]
Hope this is the right place to post this, but I'm trying to use ES2015 in my Gulpfile with buble, but I get the error `Failed to load external module buble/register`

package.json
```
"devDependencies": {
    ...
    "buble": "^0.13.2",
    "gulp": "^3.9.1",
    ...
}
```

**Comment by jonschlinkert** [comment]
@WolfieZero would you mind opening a new issue?

**Pull request merged**
